# Vectors (Rank 1 Tensors)

### NumPy

In [1]:
import numpy as np

In [2]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
np.shape(x)

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0]

25

In [7]:
type(x[0])

numpy.int32

#### Vector Transposition

Transposing a one-dimensional array will have no effect.

In [8]:
x_t = x.T
x_t

array([25,  2,  5])

In [9]:
x_t.shape

(3,)

A one-dimensional array represented as a two-dimensional one (2D matrix) can be used for transposition to be effective.

In [11]:
y = np.array([[25, 2, 5]])
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [13]:
y.shape

(1, 3)

In [12]:
y_t.shape

(3, 1)

#### Zero Vectors

Can be generated with the np.zeros() function. No effect when added to other vectors.

In [14]:
z = np.zeros(3)
z

array([0., 0., 0.])

### PyTorch

In [15]:
import torch

In [16]:
x_pt = torch.tensor([23, 2, 5])
x_pt

tensor([23,  2,  5])

In [19]:
type(x_pt)

torch.Tensor

In [20]:
x_pt.shape

torch.Size([3])

In [21]:
x_pt.T

C:\Users\ADITYA\AppData\Local\Temp\ipykernel_18060\564006262.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3575.)
  x_pt.T


tensor([23,  2,  5])

In [22]:
y_pt = torch.tensor([[25, 2, 5]])

In [23]:
y_pt.T

tensor([[25],
        [ 2],
        [ 5]])

### TensorFlow

In [17]:
import tensorflow as tf

In [18]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

In [24]:
type(x_tf)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [25]:
x_tf.shape

TensorShape([3])

In [26]:
# tf.transpose(x_tf, perm=[1,0])                # Throws an error due to incorrect number of dimensions for transposition

InvalidArgumentError: {{function_node __wrapped__Transpose_device_/job:localhost/replica:0/task:0/device:CPU:0}} transpose expects a vector of size 1. But input(1) is a vector of size 2 [Op:Transpose]

In [27]:
y_tf = tf.Variable([[25, 2, 5]])

In [28]:
tf.transpose(y_tf, perm=[1,0])

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[25],
       [ 2],
       [ 5]])>